import "./css/style.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local"
import './css/style.css'
import './css/additional-styles/theme.css'
import './css/additional-styles/utility-patterns.css'
import Header from "@/components/ui/header";
import LightPillar from "@/components/ui/LightPillar";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const nacelle = localFont({
  src: [
    {
      path: "../public/fonts/nacelle-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/nacelle-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/nacelle-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/nacelle-semibolditalic.woff2",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-nacelle",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${nacelle.variable} bg-transparent font-inter text-base text-[#2b2216] antialiased`}
      >
        <div className="relative min-h-screen overflow-hidden bg-[#fffdf7]">
          <div className="pointer-events-none absolute inset-0  sm:block hidden">
              {/* <LightPillar

                topColor="White"
                bottomColor="white"
                intensity={1}
                rotationSpeed={0.01}
                glowAmount={0.005}
                pillarWidth={3.0}
                pillarHeight={0.4}
                noiseIntensity={1}
                pillarRotation={0}
                interactive={false}
                mixBlendMode="normal"
              /> */}
          </div>
          <div className="relative z-10 flex min-h-screen flex-col overflow-hidden pt-14 supports-[overflow:clip]:overflow-clip">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
